[package]
name = "rustic_bitmap"
version = "0.1.0"
authors = ["Xiokka <xiokka_contact@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rustic_bitmap"
path = "src/lib.rs"
